### DISCUSSION TITLE
Running the last version of the docker will cause the computer to stop within minutes

### DISCUSSION THREAD

**Discussion by utsi09** [carla-simulator/carla#8831] [Q&A]
If you get the late image from the docker and run it in docker components, it runs, but if it's short, the connected monitors stop within seconds to minutes. I see the mouse moving on the main laptop, but nothing else runs. I was wondering if I could get some help. My docker-compose.yml code is as follows.
```
version: "3.9"

services:
  carla:
    container_name: carla_simulator
    image: carlasim/carla:latest
    privileged: true
    runtime: nvidia 
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./workspace:/home/workspace
    stdin_open: true
    tty: true
    command: /bin/bash -c "./CarlaUE4.sh"
``` 
In addition, the following code is an executable sh file.
```
#!/bin/bash

echo "[INFO] Allowing X11 for local docker root user..."
xhost +local:root
# export DISPLAY=:0

echo "[INFO] Starting CARLA container with docker compose..."
docker compose up


```
