### ISSUE TITLE
CARLA Server in CI Pipeline

### ISSUE THREAD

**Issue by christiangeller** [carla-simulator/carla#6076]
Hello everyone, 

I want to use CARLA in a GitLab CI pipeline for testing some own implemented functions. This requires a running CARLA Server. 

The CI Job is based on a Docker Image with CARLA installed as well as containing my application. When starting the CARLA server (with RenderOffScreen flag) and "&" flag (for background activity), the server stops when executing a second command to launch my application. 

Has anyone experience with CARLA in CI pipeline context or in general with multiple parallel processes in CI pipelines? 

Here is my job definition from the gitlab-ci.yml file:
```
testing:carla:
  stage: Testing
  image: $image_carla_interface:ci  # this image contains carla and all other stuff
  script:
    - bash /home/user/carla/setup.sh
    - source /home/user/carla/setup.sh
    - echo "Starting CARLA server"
    - /home/user/carla/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping CarlaUE4 vulkan -nosound -RenderOffScreen &
    - python /builds/carla/carla-interface/carla_examples/test.py
 ```

Thanks for your support or ideas!
