### ISSUE TITLE
Issues using Vulkan drivers from `carla` Docker image on Ubuntu 22.04 with NVIDIA GPU

### ISSUE THREAD

**Issue by benrbray** [carla-simulator/carla#6234]
# System Information

Basic Information
* Carla Version:  `0.9.14`
* Platform/OS: Ubuntu 22.04
* GPU:  NVIDIA GeForce RTX 3060 Laptop, confirmed to [support Vulkan](https://vulkan.gpuinfo.org/listreports.php?devicename=NVIDIA+GeForce+RTX+3060+Laptop+GPU)

```
$ nvidia-smi
Wed Feb 22 17:03:11 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0    15W /  65W |   1142MiB /  6144MiB |     45%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2205      G   /usr/lib/xorg/Xorg                506MiB |
|    0   N/A  N/A      2667      G   /usr/bin/gnome-shell               92MiB |
|    0   N/A  N/A      3933      G   ...698086980056340607,131072      540MiB |
+-----------------------------------------------------------------------------+

```

```
$ vulkaninfo --summary
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.204


Instance Extensions: count = 19
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers: count = 3
--------------------------
VK_LAYER_INTEL_nullhw       INTEL NULL HW                1.1.73   version 1
VK_LAYER_MESA_device_select Linux device selection layer 1.3.211  version 1
VK_LAYER_MESA_overlay       Mesa Overlay layer           1.3.211  version 1

Devices:
========
GPU0:
	apiVersion         = 4206816 (1.3.224)
	driverVersion      = 92282885 (0x5802005)
	vendorID           = 0x8086
	deviceID           = 0x9a60
	deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName         = Intel(R) UHD Graphics (TGL GT1)
	driverID           = DRIVER_ID_INTEL_OPEN_SOURCE_MESA
	driverName         = Intel open-source Mesa driver
	driverInfo         = Mesa 22.2.5
	conformanceVersion = 1.3.0.0
	deviceUUID         = 5518e060-88cf-2c86-d6ac-84447a144945
	driverUUID         = bb1fb619-2f58-f756-9577-c140947c997e
GPU1:
	apiVersion         = 4206816 (1.3.224)
	driverVersion      = 1 (0x0001)
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 15.0.6, 256 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 22.2.5 (LLVM 15.0.6)
	conformanceVersion = 1.3.1.1
	deviceUUID         = 6d657361-3232-2e32-2e35-000000000000
	driverUUID         = 6c6c766d-7069-7065-5555-494400000000
GPU2:
	apiVersion         = 4206816 (1.3.224)
	driverVersion      = 2203403008 (0x83554300)
	vendorID           = 0x10de
	deviceID           = 0x2520
	deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName         = NVIDIA GeForce RTX 3060 Laptop GPU
	driverID           = DRIVER_ID_NVIDIA_PROPRIETARY
	driverName         = NVIDIA
	driverInfo         = 525.85.12
	conformanceVersion = 1.3.3.1
	deviceUUID         = ca5871d6-130c-b7fe-a8d7-4d90050e6dae
	driverUUID         = cebda6db-dfde-5d5e-b804-0471e8100ab8

```

# Steps to Reproduce

At first, I attempted to follow the [Carla in Docker](https://carla.readthedocs.io/en/0.9.14/build_docker/) instructions from the docs, but ran into a number of issues.  Ultimately I was able to make the most progress by following this ["Carla simulator in Docker in 2023"](https://antc2lt.medium.com/carla-simulator-in-docker-in-2023-1f11f240b2df) article.

### Installing Nvidia Container Toolkit

```
$ distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
    && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
    && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
$ sudo apt-get update
$ sudo apt-get install -y nvidia-docker2
$ sudo apt-get install -y nvidia-container-toolkit
$ sudo systemctl restart docker
```

Confirmed to be working with `nvidia-smi` from inside a container:

```
$ sudo docker run --rm --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi
[sudo] password for ben: 
Wed Feb 22 08:06:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P5    13W /  65W |    857MiB /  6144MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

### Running Carla

I'm running the `carlasim/carla:0.9.14` docker image using a modified version of the `docker-compose.yml` file from the article linked above:

```yaml
version: '3.8'

services:
  carla:
    image: carlasim/carla:0.9.14
    command: ["bash", "./CarlaUE4.sh", "-vulkan", "--gpus=\"all,'capabilities=compute,utility,graphics,display'\""]
    # runtime: nvidia
    # ports:
    #  - "2000-2002:2000-2002"
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1 # Fix a bug with QT
      - SDL_VIDEODRIVER=x11
      # debugging vulkan issues (https://forums.gentoo.org/viewtopic-t-1147947-start-0.html)
      #- ENABLE_DEVICE_CHOOSER_LAYER=1
      #- VULKAN_DEVICE_INDEX=2
    user: "carla"
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d # https://github.com/microsoft/AirSim/issues/4236
      - /home/${USER}:/home/${USER}:rw                  # share your home with write permissions
    privileged: true
    network_mode: "host"
    stdin_open: true
    tty: true
```

Here is the result of running the container:

```
$ sudo docker compose up
[+] Running 1/0
 ⠿ Container carla-carla-1  Created                                                                                                   0.0s
Attaching to carla-carla-1
carla-carla-1  | 4.26.2-0+++UE4+Release-4.26 522 0
carla-carla-1  | Disabling core dumps.
carla-carla-1  | sh: 1: xdg-user-dir: not found
carla-carla-1 exited with code 1
```

I also receive the following error dialog, which appears to come from Unreal Engine:

![image](https://user-images.githubusercontent.com/221963/220560303-699d10ee-2bea-4b0f-a306-c3528fdf3bc7.png)

I'm not sure why there are ICD problems, given that I am passing `-v /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d` to the container, as suggested by [this Github issue](https://github.com/microsoft/AirSim/issues/4236).  The contents of this directory on the host are:

```
$ ls /usr/share/vulkan/icd.d
intel_icd.x86_64.json  lvp_icd.x86_64.json  nvidia_icd.json  nvidia_layers.json  radeon_icd.x86_64.json
$ cat /usr/share/vulkan/icd.d/nvidia_icd.json 
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.224"
    }
}
$ cat /usr/share/vulkan/icd.d/nvidia_layers.json 
{
    "file_format_version" : "1.0.0",
    "layer": {
        "name": "VK_LAYER_NV_optimus",
        "type": "INSTANCE",
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.224",
        "implementation_version" : "1",
        "description" : "NVIDIA Optimus layer",
        "functions": {
            "vkGetInstanceProcAddr": "vk_optimusGetInstanceProcAddr",
            "vkGetDeviceProcAddr": "vk_optimusGetDeviceProcAddr"
        },
        "enable_environment": {
            "__NV_PRIME_RENDER_OFFLOAD": "1"
        },
        "disable_environment": {
            "DISABLE_LAYER_NV_OPTIMUS_1": ""
        }
    }
}
```

The `libGLX_nvidia.so.0` library is also available, as I have installed `libnvidia-gl-525`:

```
$ ldconfig -p | grep libGLX_nvidia
	libGLX_nvidia.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
	libGLX_nvidia.so.0 (libc6) => /lib/i386-linux-gnu/libGLX_nvidia.so.0
```

I've tried a number of different solutions found online, but at this point I'm at a loss for what to try next.  Any help would be appreciated, thank you!
