### ISSUE TITLE
Expected FPS with LIDAR enabled?

### ISSUE THREAD

**Issue by rohanb2018** [carla-simulator/carla#634]
I have been consistently getting low (below real-time) frame rates when trying to run CARLA with LIDAR enabled, and I want to see whether this is the expected behavior with the CARLA LIDAR sensor or whether there is something with my CARLA/machine setup that is awry.

My software setup involved running a server instance from the Unreal Editor, and connecting to the server using the `carla_ros_bridge` ROS client.

-----------------------

CARLA server configuration:
- Synchronous mode: True
- Quality Level: Low
- Sensors: LIDAR only
- Map: Town01
- Vehicles: 1, Pedestrians: 10

The LIDAR configuration that I used was similar to that of an HDL-64E LIDAR:

```
lidar_0:
  SensorType: LIDAR_RAY_CAST
  carla_settings:
    Channels: 64
    Range: 120
    PointsPerSecond: 1000000
    RotationFrequency: 20
    UpperFovLimit: 2.0
    LowerFovLimit: -24.8
    PositionX: 0.0
    PositionY: 0
    PositionZ: 1.50
    RotationPitch: 0
    RotationYaw: 0
    RotationRoll: 0
```

The frame rates that I was getting, as a function of the CARLA server fixed FPS, are as follows:

**Fixed FPS** | **Measured FPS**
--- | --- 
20 | 4.950
15 | 3.344
10 | 2.463
5 | 1.238

Machine spec:
- GPU: Geforce GTX1080
- CPU: Intel Core i7-7820X
- OS: Ubuntu 16.04

-----------------------
Other observations:

- I tried disabling the rendering, and that didn't have much of an effect. 
- I noticed that the frame rate increased as the number of LIDAR points decreased, indicating that the ray-casting used for the CARLA LIDAR might be the bottleneck. 
- CARLA ran at anywhere from 2-5x real-time when I enabled the camera only.

Any help would be appreciated, and I'd be happy to provide more information about my setup and system specs if that would be helpful. Thanks!
